version: '3'

services: 
  myredis:
    image: 'redis:alpine'
  mypostgres:
    restart: always
    image: 'postgres:alpine'
    environment: 
        - POSTGRES_PASSWORD=Smoku1!1
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
    volumes: 
        - C:/Users/tplawczyk/postgresdata:/var/lib/postgresql/data
    ports:
        - "6432:5432"
  mynginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mynginx
    ports:
        - "9090:80"
     
        
   
  mybackend:
    build: 
      dockerfile: Dockerfile
      context: ./mybackend
    depends_on: 
      - 'mypostgres'
      - 'myredis'
      
    volumes:
      - /opt/app/node_modules 
      - C:/Users/tplawczyk/newapp/mybackend:/opt/app
    environment: 
      - POSTGRES_HOST=mypostgres
      - POSTGRES_PASSWORD=Smoku1!1
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - REDIS_HOST=myredis

  myfrontend:
      build:
        dockerfile: Dockerfile.dev
        context: ./myfrontend
      
        
   
      volumes:
        - /opt/app/node_modules
        - C:/Users/tplawczyk/newapp/myfrontend:/opt/app

        